{
  username = "User";
  userfullname = "HryshcIlya";
  useremail = "175040986+HryshcIlya@users.noreply.github.com";
  # generated by `mkpasswd -m scrypt --rounds=11`
  # https://man.archlinux.org/man/crypt.5.en
  initialHashedPassword = "$7$GU..../....kl8ezyhSFRkmTzIFwEOg2/$lpr07QL2Ghh.1K.m9lU4VdD10c/z5p2Yy/lwOrbbOt2";
}
